# === File: render.yaml ===

services:
  - type: web
    name: averisaxiom-agent
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run streamlit_ui.py --server.port $PORT --server.address 0.0.0.0"
    disk:
      name: averisaxiom-disk
      mountPath: /mnt/data

  - type: cron
    name: averisaxiom-dailyreport
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    schedule: "0 7 * * *"
    command: "python daily_report.py"
    disk:
      name: averisaxiom-disk
      mountPath: /mnt/data

disks:
  - name: averisaxiom-disk
    mountPath: /mnt/data
    sizeGB: 1
