blueprintVersion: 1

services:
  - type: web
    name: averisaxiom-agent
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run streamlit_ui.py --server.port $PORT --server.address 0.0.0.0"
    mounts:
      - name: averisaxiom-disk
        path: /mnt/data

  - type: cron
    name: averisaxiom-dailyreport
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    schedule: "0 7 * * *"
    startCommand: "python daily_report.py"
    mounts:
      - name: averisaxiom-disk
        path: /mnt/data

volumes:
  - name: averisaxiom-disk
    sizeGB: 1
