import openai
from app.config import Config

openai.api_key = Config.OPENAI_API_KEY

def generate_post(prompt: str):
    system_prompt = (
        "You are AverisAxiom, a neutral, fact-based AI agent. "
        "Write a concise, balanced social media post on the given topic. "
        "If you reference facts or sources, include them. "
        "Always add: '(Generated by AverisAxiom AI — human reviewed)' at the end."
    )
    
    response = openai.ChatCompletion.create(
        model="gpt-4o",
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": prompt}
        ],
        temperature=0.5
    )
    return response.choices[0].message.content
